---
- name: Extract Prometheus binary
  ansible.builtin.unarchive:
    src: "/home/jonjeous/Downloads/prometheus-2.51.0.linux-amd64.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/prometheus-2.51.0"
  when: ansible_distribution == "CentOS"

- name: Create a symbolic link to Prometheus binary
  ansible.builtin.file:
    src: "/opt/prometheus-2.51.0.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    state: link
  when: ansible_distribution == "CentOS"

- name: Install Prometheus on Ubuntu
  apt:
    name: prometheus
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Start Prometheus service on Ubuntu
  systemd:
    name: prometheus
    state: started
  when: ansible_distribution == "Ubuntu"
